### ISSUE TITLE
Not working on FF 102 and 103

### ISSUE THREAD

**Issue by luispabon** [waymondrang/DocsAfterDark#10]
I installed this for the first time on Firefox 102 beta9 and it does not seem to be working - loading up a google spreadsheet then changing backround to the several options doesn't seem to do anything. Same thing with Firefox nightly (103).

I'm on wayland, if that makes any difference.

**Comment by waymondrang** [comment]
Hello,

The extension was not built for Google Sheets. It only works on Google Docs.

Raymond
