### ISSUE TITLE
Opera Support?

### ISSUE THREAD

**Issue by chiyeon** [waymondrang/docsafterdark#11]
The readme lists support for the Opera browser as in progress, with:

> An Opera release is currently awaiting approval.

Are there any updates on an Opera full release?

**Comment by waymondrang** [comment]
![image](https://user-images.githubusercontent.com/57642450/181166049-45d7ba45-25e9-49f0-bcbf-72ca0e66378b.png)
 
# Transcription

Status has changed for DocsAfterDark
DocsAfterDark v0.3.30 on Opera Developer: Published.
DocsAfterDark v0.3.30 on Opera Next: Published.

Moderator's note:

Your extension needs to be manually reviewed and moderated before it can be added to Opera Stable. It is currently only viewable and available for download in Opera Developer and Opera Beta.

 Feb 23, 2022 7:34:03 PM UTC
