### ISSUE TITLE
Sheets?

### ISSUE THREAD

**Issue by EngineerJack** [waymondrang/docsafterdark#12]
This is a question instead of an issue. I was going to phrase it as an issue, being something to the effect of this doesn't work in sheets, but after researching other similar addons I realized this is how it is for all of them, at least that I've found.

So my question is, is there any way to make this work with Sheets?

If not, do you plan on adding Sheets?

I know we can use addons such as Dark Reader, which works well enough, but I hate how colors are inverted, which makes it difficult to format when using colors.

If anyone knows of a better way to do this, I would appreciate knowing how.

**Comment by waymondrang** [comment]
Hello,

I plan on focusing only on Google Docs and do not plan to add support for Google Sheets. Sheets is a complex website that is different from Google Docs—the current stylesheet of DocsAfterDark would not work with Sheets.

Thank you!

Raymond
