### ISSUE TITLE
Extension not applying dark theme correctly inside of firefox.

### ISSUE THREAD

**Issue by linusrg1** [waymondrang/docsafterdark#15]
![Dark gdocs extension issue](https://user-images.githubusercontent.com/67347319/192556916-2834377c-c374-409d-8a17-bc588228bf4b.jpg)
This is basically it here. For whatever reason it is not applying correctly. 
I have the latest extension version available in the Firefox addons store, and I am currently on Firefox 104.0.2. I am also running openSUSE tumbleweed, not sure if that matters though.

**Comment by waymondrang** [comment]
Thank you for opening an issue. You may be using multiple dark mode extensions—may I ask which extensions you have installed on Firefox?

**Comment by linusrg1** [comment]
I also have dark reader installed, but I have it disabled for google docs.

**Comment by waymondrang** [comment]
That is strange. What version of DocsAfterDark are you using? Please confirm that this issue is not caused by conflicting dark mode extensions by disabling all other extensions from the Firefox "Manage Your Extensions" page here `about:addons`.

**Comment by linusrg1** [comment]
Yah same issue, even with Dark Reader fully disabled. Also this extension is not themeing the Google Docs home page. (The area where you can create a new document, or open an existing one) But to be honest, I don't even know if it is supposed to theme this area of Google Docs. Also I am using version 0.5.2 of the DocsAfterDark extension. (Thanks for your help by the way!)

**Comment by waymondrang** [comment]
The extension does not affect the home page of Google Docs. I would recommend creating a new profile on Firefox and then installing DocsAfterDark. 

To create a new Firefox profile, go to `about:profiles` and click "Create a New Profile." 

Follow the prompts and then click "Launch profile in new browser" underneath your new profile. 

Add DocsAfterDark [here](https://addons.mozilla.org/en-US/firefox/addon/docsafterdark/) and then open a document on Google Docs. 

Please let me know if this works!

**Comment by linusrg1** [comment]
Well you were indeed right, it was something to do with my current profile. Don't know what as Dark Reader was disabled, but it was definitely something. Here is how it looks in a new profile:
![Github DocsAfterDark extension issue 2](https://user-images.githubusercontent.com/67347319/192780594-4f4abfeb-d315-49d8-9792-4a596aa9177c.png)

As you can see it looks perfect! The option to modify how the document itself looks works too!
![Github DocsAfterDark extension issue 3](https://user-images.githubusercontent.com/67347319/192783218-c05765b5-336f-40ff-90d4-5b4f349e3ea8.jpg)

I do not know what the issue is exactly but I will do the logical thing of disabling all my extensions and then report back on how that goes.

**Comment by linusrg1** [comment]
I'm so sorry! There was a Google Docs dark mode extension that I was using before this one that I thought I had uninstalled before installing this one, but apparently I hadn't. So I am pretty sure that that other extension still had priority over this one. Meaning that the extremely buggy way it uses dark mode was still being used. I feel bad for wasting your time with this.

**Comment by waymondrang** [comment]
Don't worry! I'm glad you were able to fix the issue. Please open another issue should another problem arise.
