### ISSUE TITLE
Document background color is only changed if "Invert" option is on

### ISSUE THREAD

**Issue by Chirunos** [waymondrang/docsafterdark#20]
Brave Browser Beta 1.57.33
DocsAfterDark 0.6.1
Windows 10 Version 2004

**Comment by waymondrang** [comment]
Hello,

Thank you for opening an issue. Can you provide screenshots or more information regarding this issue?

**Comment by rorybd** [comment]
On Microsoft Edge as well, the 'document background' feature does not work. The 'Invert' and 'Grayscale' buttons do, however, work as intended.
![image](https://user-images.githubusercontent.com/124809440/217603843-280137e8-acc1-493f-a5b1-1bf0ade985a4.png)

**Comment by Gersonzao** [comment]
"Invert" unchecked:
![image](https://github.com/waymondrang/docsafterdark/assets/85644671/c703e9e5-5009-485e-9b50-6fbc34c2ec3d)
"Invert" checked:
![image](https://github.com/waymondrang/docsafterdark/assets/85644671/9b54585d-b934-4022-9429-0925b40c17ba)

**Comment by realNZZN** [comment]
This also happens with DocsAfterDark v0.6.3 on Vivaldi 6.5.3206.57 (Chromium 120)

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue. If you are using a Chromium-based browser (such as Vivaldi or Brave), this is an expected side-effect of the invert function. However, if you are using Firefox, the invert function should not also invert images. If you are using Firefox and still experience image invert issues after the v1.0.0 update, please feel free to open another issue.
