### ISSUE TITLE
Text / Background disparity in Dictionary and Citations

### ISSUE THREAD

**Issue by Ion-1** [waymondrang/docsafterdark#21]
You type white text on a white background. Drop down options in Citations are white with white text, but hovering over/selecting them returns them to normal dark mode (until you are not selecting an option/hovering over the drop-down option). Most buttons are also dark mode as expected.

DocsAfterDark v0.5.3,
Default, no invert, showing document border and normal button height.

**Comment by waymondrang** [comment]
Thank you for opening an issue. I have confirmed the issue regarding the citations panel. Just for clarification, is there also an issue regarding typing text on the document?

**Comment by skalameraion** [comment]
No, just typing text on the Dictionary panel too.

**Comment by waymondrang** [comment]
Thank you for the clarification. This issue will be worked on and patched in a future update.

**Comment by waymondrang** [comment]
The citations panel has not been fixed, yet.

**Comment by vvirtues** [comment]
Is this still being worked on?

**Comment by waymondrang** [comment]
Hello, thank you for your patience! This (long-overdue) bug has finally been addressed in the latest update, v1.0.0. However, if you are still experiencing this or any other problems with the new update, please feel free to open another issue.
