### ISSUE TITLE
DAD no longer inverts the page colors

### ISSUE THREAD

**Issue by Prezombie** [waymondrang/docsafterdark#23]
Brand new doc, everything is inverted except the page.

It worked last time I used it back in October.

![image](https://user-images.githubusercontent.com/5942485/210584241-345132eb-8677-4e0f-806d-b610ad6c89cc.png)

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue! If you are still experiencing this problem, please feel free to open another issue.
