### ISSUE TITLE
Suggested Comment Responses Not Affected

### ISSUE THREAD

**Issue by rorybd** [waymondrang/docsafterdark#25]
The buttons that suggest automatic responses for comments do not match the dark theme, remaining white.
[Microsoft Edge]
![image](https://user-images.githubusercontent.com/124809440/217864265-bb31b2a4-f9c2-425b-a083-fc409bc14b83.png)

**Comment by rorybd** [comment]
The 'More Fonts' menu is similarly mismatching, as are most of the menus under 'Tools' (e.g. Dictionary), the 'drawings' menu, and several others.
![image](https://user-images.githubusercontent.com/124809440/217868156-dc5c32a8-1f27-44cc-a41c-b6739424724c.png)

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue! The lack of dark mode for the fonts modal is expected behavior, due to difficultly of implementation. If you are experiencing any other problems, please feel free to open another issue.
