### ISSUE TITLE
Inverted colors of images in a doc.

### ISSUE THREAD

**Issue by Pyblo** [waymondrang/docsafterdark#26]
On Chrome, any images I am inserting into document have also inverted colors. This is the only thing that I find problematic, everything else works super nice:
![image](https://user-images.githubusercontent.com/767777/220903095-01dca422-e97e-42e4-9378-2ad29f48e9e9.png)

**Comment by s5706820** [comment]
just here to say that
0.6.0
on edge Version 110.0.1587.69 (Official build) (64-bit)
also have this issues

**Comment by vurtomatic** [comment]
Same on Firefox v120. DocsAfterDark v0.6.2

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue. If you are using a Chromium-based browser, this is an expected side-effect of the invert function. However, if you are using Firefox, the invert function should not also invert images. If you are using Firefox and still experience image invert issues after the v1.0.0 update, please feel free to open another issue.

**Comment by snaphat** [comment]
The reason Firefox does not invert the images is that they do not render using canvas. This issue is workaroundable.

See my comment here:

> From: https://github.com/darkreader/darkreader/issues/8730#issuecomment-2791327156
> ----
> The following userscript tricks Google Docs into rendering the document as it does in Firefox. This causes images to be rendered as `<img>` elements instead of using `canvas`, while text continues to be rendered using canvas.
> 
> ```
> // ==UserScript==
> // @name         Force Google Docs Canvas Fallback
> // @description  Spoofs Firefox user agent to make Google Docs stop using canvas for images, while still using canvas for text rendering
> // @version      0.0.1
> // @match        https://docs.google.com/*
> // @run-at       document-start
> // ==/UserScript==
> 
> navigator.__defineGetter__("userAgent", () => "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0");
> ```
> 
> The above User-agent switcher extensions in prior comments do not work because they only modify the HTTP User-Agent header. They do not override the `navigator.userAgent` property in JavaScript, which is what Google Docs actually checks as of this writing.
> 
> A couple of alternative extensions that do support this behavior are:
> 
> * [UserAgent-Switcher (GitHub)](https://github.com/ray-lothian/UserAgent-Switcher), which can override navigator.userAgent at the JavaScript level.
> * [User-Agent Switcher by BrowserNative](https://browsernative.com/user-agent-switcher-extension/), which supports removing or modifying navigator properties entirely.
