### ISSUE TITLE
Images are Blank

### ISSUE THREAD

**Issue by chiyeon** [waymondrang/DocsAfterDark#3]
When dark mode is on, images appear as completely white.

![image](https://user-images.githubusercontent.com/44148480/152428755-1e685ce0-5922-4b3a-9960-f29f82911529.png)

**Comment by waymondrang** [comment]
Thank you for reporting this issue! I have found a fix and will update the extension as soon as possible.

**Comment by waymondrang** [comment]
This issue has been fixed in the [latest release]( https://github.com/waymondrang/DocsAfterDark/releases/tag/v0.3.1).
