### ISSUE TITLE
Outline Subheader Color Unreadable

### ISSUE THREAD

**Issue by ARTINKEL** [waymondrang/docsafterdark#31]
My settings:

![image](https://user-images.githubusercontent.com/31296090/225113194-79d1be42-81bb-4bf6-8dc3-33efc1e9a4f6.png)

The result:

![image](https://user-images.githubusercontent.com/31296090/225113310-c3f3315b-0cf6-4035-b95b-80b28402f63f.png)

I would expect the color to also be white like the level 1 header above it.

This is what it looks like without the extension:

![image](https://user-images.githubusercontent.com/31296090/225113539-d874606d-f6fc-44fc-aa6d-1c16f507be39.png)

**Comment by waymondrang** [comment]
Thank you for the detailed reporting of this issue. This will be fixed in the next update of DocsAfterDark.

**Comment by zipswich** [comment]
I have the same issue. I posted the question to a wrong place:☺️
https://support.google.com/docs/thread/308732100/how-to-change-the-outline-text-color

**Comment by waymondrang** [comment]
Closing this issue as it seems to be fixed. If you are still experiencing this or any other problems, please feel free to open another issue!
