### ISSUE TITLE
Chinese input tools button hard to see with extension on

### ISSUE THREAD

**Issue by amadeusjustinn** [waymondrang/docsafterdark#34]
The Chinese input tools button stays dark with the extension on:
![image](https://user-images.githubusercontent.com/67861264/227797552-28cd9d30-660f-4a94-8695-dfdf27469692.png)
This is what the button looks like with the extension off:
![image](https://user-images.githubusercontent.com/67861264/227797589-68d732f2-16d6-4f4f-ad0a-585b1cc22c9c.png)

**Comment by waymondrang** [comment]
Closing this issue as it should be fixed. If you are still experiencing this or any other problems, please feel free to open another issue!
