### ISSUE TITLE
Ruler does not get changed on Firefox anymore

### ISSUE THREAD

**Issue by sSasha-uwu** [waymondrang/docsafterdark#36]
![image](https://github.com/waymondrang/docsafterdark/assets/112319694/c4793e84-e3c0-4d8d-a475-09d8f23ef2be)

Not sure what changed, but I opened Firefox today and now this is happening. For now I've just hidden the ruler on docs.

**Comment by waymondrang** [comment]
Thank you for opening this issue. Are you still experiencing this?

**Comment by sSasha-uwu** [comment]
Yes.

**Comment by waymondrang** [comment]
Unfortunately, I am unable to replicate this issue on Firefox. Do you have any other dark mode extensions installed?

**Comment by nizamiza** [comment]
This issue appears in Arc as well. The search icon is also white btw.

<img width="1327" alt="Screenshot 2023-10-09 at 22 06 28" src="https://github.com/waymondrang/docsafterdark/assets/13175359/c75cf4fb-e347-410b-a242-91f80d66e1cf">

**Comment by infinitysnapz** [comment]
![image](https://github.com/waymondrang/docsafterdark/assets/26030701/c73ecc4e-868a-4b33-8770-40692e800757)
i too have this issue with vivaldi

**Comment by Narotiza** [comment]
Getting this issue too, but only when the page setup mode (accessed through File -> Page Setup) is set to pageless. It's fine otherwise

**Comment by waymondrang** [comment]
Thank you for everyone's input! I have released a fix for the ruler issue in [v0.6.3](https://github.com/waymondrang/docsafterdark/releases/tag/v0.6.3), which has been submitted to the Chrome and Firefox extension stores for approval. The process typically takes several days, especially for Chrome, for users to receive the update. Thank you for your understanding!
