### ISSUE TITLE
Page setup dialog text unreadable in dark mode

### ISSUE THREAD

**Issue by ecols33** [waymondrang/docsafterdark#39]
When you go File>Page Setup, and select Pageless, the dialog has the text 

> The pageless format allows you to add wide images and tables, and consume content without the interruption of page breaks

The text is nearly unreadable in dark mode - it wasn't changed to be white/gray text when dark mode is activated.

<img width="436" alt="Screenshot 2023-10-24 at 2 47 42 PM" src="https://github.com/waymondrang/docsafterdark/assets/12535799/64070127-03f5-4cbd-b07c-c26c9249292c">

**Comment by waymondrang** [comment]
Closing this issue as it should be fixed. If you are still experiencing this or any other problems, please feel free to open another issue!
