### ISSUE TITLE
Explore/Link objects/citations menu is white

### ISSUE THREAD

**Issue by CodeKid2024** [waymondrang/docsafterdark#42]
![Screenshot 2023-12-06 130303](https://github.com/waymondrang/docsafterdark/assets/81322639/3ca84e94-7110-419b-976f-8272c0122cfa)

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue! However, I will close this issue (even though it is not yet resolved) as it is a duplicate of #40.
