### ISSUE TITLE
Theme isn't remembered for new tabs

### ISSUE THREAD

**Issue by BMorearty** [waymondrang/docsafterdark#45]
Using Firefox, changing the theme isn't "sticky" when opening a new doc in another tab.

Steps to reproduce:

1. Open a Google doc, Docs After Dark it sets the theme to Dark.
2. Click the toggle in the lower left to set it to Light.
3. In a new tab, open a different Google Doc.

RESULT: the 2nd Google Doc opens in Dark mode even though I’ve just set the mode to Light.
EXPECTED RESULT: global toggle that is maintained across tabs.

**Comment by waymondrang** [comment]
Hello, 

The lower left toggle is local to the current page and will reset if the page refreshes. To have your theme preference persist across tabs, use the Global Toggle in the extension's pop-up menu. I hope this helps! 

![image](https://github.com/waymondrang/docsafterdark/assets/57642450/029a14da-90b0-48c4-94ac-c549a33d0491)
