### ISSUE TITLE
Chapter selection unsupported

### ISSUE THREAD

**Issue by violetinreal** [waymondrang/docsafterdark#46]
The chapter bar to the left is no longer working. It was before, but now it appears as the default white in all settings.

![image](https://github.com/waymondrang/docsafterdark/assets/103341205/c9edbd5c-7b1a-45c9-bced-4808563fa555)
![image](https://github.com/waymondrang/docsafterdark/assets/103341205/05acbcb8-2275-469a-a6fe-89e4d5aa9ec5)
![image](https://github.com/waymondrang/docsafterdark/assets/103341205/89679d6e-8f9a-4de1-8646-a0272263d690)

This is a major bug. It severely impacts my workflow.

**Comment by littlelapin** [comment]
having this same issue! :( guess something changed on google's end?

**Comment by waymondrang** [comment]
Thanks for opening up an issue regarding the missing dark mode. This issue has been resolved in [v0.6.3](https://github.com/waymondrang/docsafterdark/releases/tag/v0.6.3), which has been submitted to the Chrome and Firefox extension stores for approval. The process typically takes several days, especially for Chrome, for users to receive the update. Thank you for your understanding!

**Comment by benoitMariaux** [comment]
Thank you very much for your responsiveness.
