### ISSUE TITLE
Summary Menu now white

### ISSUE THREAD

**Issue by OKaysional** [waymondrang/docsafterdark#47]
Only happened in the last few days, but now the summary sidebar background is showing up white, maybe an update on drive itself? 
I'm on firefox 122 on windows
![Screenshot_79](https://github.com/waymondrang/docsafterdark/assets/151196713/a046978c-f823-4b10-af8c-d691ef0e2617)

**Comment by KosmoKhaos** [comment]
I'm also having this problem so it must be something broken with a firefox update

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue. This issue has been fixed and its successor issue (document tabs) has been fixed in the latest update, v1.0.0.
