### ISSUE TITLE
Quick Sharing Actions Button Broken

### ISSUE THREAD

**Issue by rorybd** [waymondrang/docsafterdark#48]
The "Quick Sharing Actions" dropdown button is no longer set to dark mode. 
![image](https://github.com/waymondrang/docsafterdark/assets/124809440/5cf968e5-cc6f-4837-820c-dcd3a90a420c)
![image](https://github.com/waymondrang/docsafterdark/assets/124809440/4bfe7bf3-a3fa-4d0a-8efd-ece04870952c)

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0. If you are still experiencing this or any other problems on the latest version, please feel free to open another issue!
