### ISSUE TITLE
Part of the share button is not dark

### ISSUE THREAD

**Issue by Quadragintillion** [waymondrang/docsafterdark#49]
The dropdown arrow on the share button is blue instead of the same grey as the rest of the share button.

**Comment by ComfortableMilk4454** [comment]
@waymondrang still happening. can you fix pls?
<img width="300" alt="image" src="https://github.com/waymondrang/docsafterdark/assets/43555540/a306f46f-8eb1-48d0-b269-648e6a9c8edf">
firefox release 125.0.3, docsafterdark v0.6.3

**Comment by waymondrang** [comment]
Hello, thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0. If you are still experiencing this or any other problems on the latest version, please feel free to open another issue!
