### ISSUE TITLE
Is support for Sheets and other Google Workspace pages still not planned?

### ISSUE THREAD

**Issue by PlayfulPiano** [waymondrang/docsafterdark#50]
Saw that you made comments that you might look into supporting them in the future on reddit, although I also saw that you have no plans of doing so within some of the issues made in this repo back in 2022. So I'm mainly wondering if this has any potential consideration for the future.

**Comment by waymondrang** [comment]
Hello, there are no current plans to support Sheets and other Google Workspace products, but I appreciate your inquiry!
