### ISSUE TITLE
Pageless mode in 0.6.3 - ruler issues and strange white bar

### ISSUE THREAD

**Issue by dan-mckean** [waymondrang/docsafterdark#52]
0.6.3 ruler is still showing all black and there's a strange white bar alongside the summary panel (you can only really see the top of it where it interrupts the black at the top of the summary bar)

![image](https://github.com/waymondrang/docsafterdark/assets/44909130/a967a589-1fcf-44ed-a4c1-9b450c9bf304)

**Comment by waymondrang** [comment]
Thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0.
