### ISSUE TITLE
Insert link text color bug

### ISSUE THREAD

**Issue by Korb** [waymondrang/docsafterdark#56]
Unselected text appears in `#f2f2f2`, which is almost indistinguishable against a white background.
![2024-06-29_12-29-44](https://github.com/waymondrang/docsafterdark/assets/3509797/6f751a1e-7951-40aa-9813-edef639b8f05)

DocsAfterDark 0.6.3 (June 27, 2024)
Mozilla Firefox 128.0b9 (64-bit)
Microsoft Windows 10.0.19045.4598

**Comment by abulka** [comment]
Really annoying bug. 
Mac, Chrome, DocsAfterDark 0.6.3

P.S. A competing extension [Dark Mode Google Docs](https://chromewebstore.google.com/detail/dark-mode-google-docs/iabnclnclchijjckhdljmocghgmgnnii) doesn't suffer this bug, so I have switched.

**Comment by Korb** [comment]
> Dark Mode Google Docs

Alas, there is no extension for Mozilla Firefox with this name.

**Comment by waymondrang** [comment]
Thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0.
