### ISSUE TITLE
Bug with a checkmark for the current document language

### ISSUE THREAD

**Issue by Korb** [waymondrang/docsafterdark#57]
The checkmark for the current language is almost indistinguishable:

![2024-07-10_20-42-38](https://github.com/waymondrang/docsafterdark/assets/3509797/49a69ea3-b7a6-4c40-87a6-2559234a3143)

DocsAfterDark 0.6.3 (June 27, 2024)
Mozilla Firefox 129.0b1 (64-bit)
Microsoft Windows 10.0.19045.4651

**Comment by waymondrang** [comment]
Thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0.
