### ISSUE TITLE
Document Details window is not inverted

### ISSUE THREAD

**Issue by Korb** [waymondrang/docsafterdark#58]
![2024-07-12_09-48-09](https://github.com/user-attachments/assets/b782e594-21d6-46b8-855e-86f1f376a06b)

DocsAfterDark 0.6.3 (June 27, 2024)
Mozilla Firefox 129.0b2 (64-bit)
Microsoft Windows 10.0.19045.4651

**Comment by waymondrang** [comment]
Thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0.
