### ISSUE TITLE
The Preferences window is not in a dark theme

### ISSUE THREAD

**Issue by Korb** [waymondrang/docsafterdark#59]
![2024-07-12_09-52-29](https://github.com/user-attachments/assets/c32ffe09-8553-4e4a-9e59-9b64ad15ebf8)

DocsAfterDark 0.6.3 (June 27, 2024)
Mozilla Firefox 129.0b2 (64-bit)
Microsoft Windows 10.0.19045.4651

**Comment by Alec42Fox** [comment]
Confirming I also have this issue. 

(also unfortunately, text in the substitutions tab, of the Preferences window, IS IN DARKMODE, but the window itself is NOT in darkmode, making it very difficult to read as well).

**Comment by waymondrang** [comment]
Thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0.

**Comment by Alec42Fox** [comment]
Thank you very much :D
