### ISSUE TITLE
Sheets support?

### ISSUE THREAD

**Issue by wdymUsername** [waymondrang/DocsAfterDark#6]
Hello,
would you consider extending your extension to support Google Sheets?

[One I managed to find](https://addons.mozilla.org/en-US/firefox/addon/darkdocs/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) that works with Sheets is quite outdated/broken, rest of them only do Docs and don't seem to have active development.

**Comment by waymondrang** [comment]
I am not currently looking to extend the extension to include Google Sheets. However, there seems to be a lot of demand for a Google Sheets dark mode, so I will consider it in the future. Thanks!
