### ISSUE TITLE
Document Tab Update from docs unreadable now

### ISSUE THREAD

**Issue by OKaysional** [waymondrang/docsafterdark#65]
I opened docs yesterday and noticed the sidebar looks bad like it's messed with ur extension, text is hard to read in my chosen colour and the header is not using the dark mode colours. Not sure if there's a fix on my end [I looked and fiddled and couldn't see anything] so I'm assuming it's just their update messing with ur code.
![Screenshot1903 09_10_24](https://github.com/user-attachments/assets/557e2d22-eee2-4a25-9720-bf243937fafb)

Also just want to say thank u for this extension it's a godsend

**Comment by rhoboat** [comment]
https://github.com/waymondrang/docsafterdark/compare/main...rhoboat:docsafterdark:patch-1 might work. I didn't open a PR, but offered a link to the compare of my fork. It's only a guide for the developer, as I'm sure I'm missing a lot of stuff. I probably need to add to non-firefox browsers and hover/active styles might be off.

**Comment by rhoboat** [comment]
OK WTH, I'll open the PR #66, as, if nothing else, it might help the dev. Apologies in advance.

**Comment by waymondrang** [comment]
Thank you for opening this issue. This issue has been addressed in the latest version, v1.0.0, which is currently pending approval in browser extension stores. I appreciate the pull request, but docs.css has been completely rewritten in this update. Thank you all for your patience and support!

**Comment by rhoboat** [comment]
Ah, sorry for missing your message @EclipseMantis and TY @waymondrang

**Comment by rhoboat** [comment]
Can I also just say, damn this olive green color is so rad.
<img width="265" alt="image" src="https://github.com/user-attachments/assets/8eb24609-6ddd-4f86-ac87-13d4d394e904" />
