### ISSUE TITLE
Add option to avoid changing document or add compatibility with "Pageless" page setup

### ISSUE THREAD

**Issue by kerbsy** [waymondrang/DocsAfterDark#7]
I would love an option that ignores changing the color of the document completely, and only turns the surrounding bars and menus to dark mode. This functionality is currently impossible when the document is set to "Pageless" instead of "Pages".

As my document color settings were already dark, I could previously use this extension with "Document Background" set on Custom with its settings blank, allowing me to keep my set document colors while turning the rest of the page to dark mode.

Now that the Document Background slider is disabled, the extension automatically changes my document; checking inverted is marginally better, but it's still affecting my font and background colors in a way that isn't ideal. It *does* still work when the document is set to "Pages", but something about the "Pageless" option changes the functionality.

I understand changes on Google's side has broken the Document Background function, but even if it returns, I think an explicit way to ignore the document instead of my blank "Custom" workaround would be nice.

### Extension Off
![off](https://user-images.githubusercontent.com/66316965/166170364-195b11c2-c334-4387-8500-150dfbb64aea.png)

### Extension On
![on](https://user-images.githubusercontent.com/66316965/166170376-2364aa9f-3370-445c-b8ff-543ccbf1c708.png)

### Extension and Inverted On
![inverted](https://user-images.githubusercontent.com/66316965/166170386-f4fd0810-0be9-4541-94f0-ddab78b5df56.png)

### Extension On and Document set to "Pages"
![image](https://user-images.githubusercontent.com/66316965/166170688-a2d8d799-ae1d-4a2c-bb85-e9f3b9ff41d2.png)

### Desired behavior
![intended](https://user-images.githubusercontent.com/66316965/166170390-9e8ac0b8-cb21-4931-97c7-cd7d8880a1df.png)

**Comment by waymondrang** [comment]
Hello,

Thank you for opening the issue, this is urgent! I was able to duplicate your issue and I've re-enabled the document background options in the extension. An update is currently in review to address this. Below is a screenshot of how the document will look in Pageless mode with a custom background color set in the extension. I appreciate the feedback!

![image](https://user-images.githubusercontent.com/57642450/166183384-3e87727a-1b9b-4b40-993b-6a4ae9a9b5a2.png)

**Comment by kerbsy** [comment]
Thank *you* so much for the rapid response and fix! Your extension has been wonderful otherwise! I love being able to keep my eyes *and* my document color schemes intact. I think my other request can be considered settled too, as the extension misbehaving with Pageless caused the concern to begin with.
