### ISSUE TITLE
Text sometimes shows up in white background

### ISSUE THREAD

**Issue by triumphantomato** [waymondrang/DocsAfterDark#9]
![Screen Shot 2022-05-10 at 11 16 59 AM](https://user-images.githubusercontent.com/91909240/167695601-6761b955-a949-411a-9a58-c1b5cff0d3b2.jpg)

First off thanks so much for Docs after Dark, this is exactly the add-on I was looking for on Firefox!

Unfortunately I have this weird issue where some of the text shows up in a white box. No matter what the background color is, this whiteboxing happens.

It doesn't happen when I start a document from scratch and I don't know how to get into this state, unfortunately...

This is happening on a document that somebody else started and has made edits on. To get it to show up I copy/pasted into a new document and then changed the text so it was something I could upload for you to see.

Do you have any suggestions? Thanks

**Comment by waymondrang** [comment]
Hello!

When pasting text into Google Docs, some attributes of the copied text, including background color, will also be transferred into the document. Without having access to your document, I am not certain if this is the issue but I would suggest these steps.

Highlight the affected text, then go to Format > Paragraph Styles > Borders and Shading. Setting the Background Color option to None should solve your problem.

Please let me know if that works for you!

**Comment by triumphantomato** [comment]
@waymondrang - perfect, this works! Thanks :) 

please consider adding this nugget to the bottom of the (already excellent!) faq - maybe in a Q&A section

Q: When enabling dark mode some of my text shows up in a white box. Why?

A: This is likely caused by copied text maintaining a background color of white. Highlight the affected text, then go to Format > Paragraph Styles > Borders and Shading. Setting the Background Color option to None should solve your problem.

**Comment by waymondrang** [comment]
I will consider adding a FAQ section in the next update. Thank you for your feedback!
